// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: tallyd/v1/events.proto

package grpcapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Event mirrors adapter.Event: a canonical, vendor-neutral billable
// occurrence. See internal/receiver's conversion helpers for the mapping.
type Event struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	EventName  string                 `protobuf:"bytes,3,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	Timestamp  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Properties *structpb.Struct       `protobuf:"bytes,5,opt,name=properties,proto3" json:"properties,omitempty"`
	// route optionally overrides routing-rule resolution, same as the
	// JSON API's "route" field. Empty means "resolve via configured rules."
	Route         []string `protobuf:"bytes,6,rep,name=route,proto3" json:"route,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_tallyd_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_tallyd_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_tallyd_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Event) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *Event) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Event) GetProperties() *structpb.Struct {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *Event) GetRoute() []string {
	if x != nil {
		return x.Route
	}
	return nil
}

type IngestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestRequest) Reset() {
	*x = IngestRequest{}
	mi := &file_tallyd_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestRequest) ProtoMessage() {}

func (x *IngestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tallyd_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestRequest.ProtoReflect.Descriptor instead.
func (*IngestRequest) Descriptor() ([]byte, []int) {
	return file_tallyd_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *IngestRequest) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type IngestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	mi := &file_tallyd_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tallyd_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_tallyd_v1_events_proto_rawDescGZIP(), []int{2}
}

var File_tallyd_v1_events_proto protoreflect.FileDescriptor

const file_tallyd_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x16tallyd/v1/events.proto\x12\ttallyd.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xe0\x01\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12\x1d\n" +
	"\n" +
	"event_name\x18\x03 \x01(\tR\teventName\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x127\n" +
	"\n" +
	"properties\x18\x05 \x01(\v2\x17.google.protobuf.StructR\n" +
	"properties\x12\x14\n" +
	"\x05route\x18\x06 \x03(\tR\x05route\"9\n" +
	"\rIngestRequest\x12(\n" +
	"\x06events\x18\x01 \x03(\v2\x10.tallyd.v1.EventR\x06events\"\x10\n" +
	"\x0eIngestResponse2G\n" +
	"\x06Events\x12=\n" +
	"\x06Ingest\x12\x18.tallyd.v1.IngestRequest\x1a\x19.tallyd.v1.IngestResponseB3Z1github.com/tallyd/tallyd/internal/grpcapi;grpcapib\x06proto3"

var (
	file_tallyd_v1_events_proto_rawDescOnce sync.Once
	file_tallyd_v1_events_proto_rawDescData []byte
)

func file_tallyd_v1_events_proto_rawDescGZIP() []byte {
	file_tallyd_v1_events_proto_rawDescOnce.Do(func() {
		file_tallyd_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tallyd_v1_events_proto_rawDesc), len(file_tallyd_v1_events_proto_rawDesc)))
	})
	return file_tallyd_v1_events_proto_rawDescData
}

var file_tallyd_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_tallyd_v1_events_proto_goTypes = []any{
	(*Event)(nil),                 // 0: tallyd.v1.Event
	(*IngestRequest)(nil),         // 1: tallyd.v1.IngestRequest
	(*IngestResponse)(nil),        // 2: tallyd.v1.IngestResponse
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 4: google.protobuf.Struct
}
var file_tallyd_v1_events_proto_depIdxs = []int32{
	3, // 0: tallyd.v1.Event.timestamp:type_name -> google.protobuf.Timestamp
	4, // 1: tallyd.v1.Event.properties:type_name -> google.protobuf.Struct
	0, // 2: tallyd.v1.IngestRequest.events:type_name -> tallyd.v1.Event
	1, // 3: tallyd.v1.Events.Ingest:input_type -> tallyd.v1.IngestRequest
	2, // 4: tallyd.v1.Events.Ingest:output_type -> tallyd.v1.IngestResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_tallyd_v1_events_proto_init() }
func file_tallyd_v1_events_proto_init() {
	if File_tallyd_v1_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tallyd_v1_events_proto_rawDesc), len(file_tallyd_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tallyd_v1_events_proto_goTypes,
		DependencyIndexes: file_tallyd_v1_events_proto_depIdxs,
		MessageInfos:      file_tallyd_v1_events_proto_msgTypes,
	}.Build()
	File_tallyd_v1_events_proto = out.File
	file_tallyd_v1_events_proto_goTypes = nil
	file_tallyd_v1_events_proto_depIdxs = nil
}
